### PR TITLE
Update GUI 

### LINKED ISSUE #17: Change to Dense Table
Change to dense table by create custom table
Screenshot from 2021-08-19 11-57-49

### PR DESCRIPTION
**Pull request by finesaaa**
Closes #17 #18 #15

### CODE REVIEW

**Review by maroqijalil — APPROVED** [review]
LGTM

**Comment by threeal** [comment]
Could you provide screenshots regarding changes you made? @finesaaa

**Comment by finesaaa** [comment]
> Could you provide screenshots regarding changes you made? @finesaaa

Screenshot from 2021-08-21 13-03-55

**Comment by finesaaa** [comment]
> > Could you provide screenshots regarding changes you made? @finesaaa
> 
> Screenshot from 2021-08-21 13-03-55

Actually, the major change is the used components to DataGrid, but there are also a few changes to the layout

**Review by threeal — APPROVED** [review]
Looks good to me.

**Pull request merged**
